insert into product(PID, PRODUCTION_DATE, Spent_time) 
values ('123554', to_date('2015-06-04', 'YYYY-MM-DD'), '22');

select * from product;

to_date('2015-03-04', 'YYYY-MON-DD');

INSERT INTO PRODUCT (PID, PRODUCTION_DATE, SPENT_TIME) 
VALUES ('832646', TO_DATE('2016-11-08', 'YYYY-MM-DD'), '55');

select E_Name from worker
where E_Name = 'Saied Hosseinipoor';

insert into produce (PID, E_Name) Values ('948975', 'Eric Kennedy');

INSERT INTO QC_CHECK (PID, E_NAME) VALUES ('948975', 'Sara Burns');

Select Education 
from tech_staff
where e_name = 'Bonnie Porter';

INSERT INTO REPAIR (PID, E_NAME, R_DATE) 
VALUES ('948975', 'Bonnie Porter', TO_DATE('2016-09-08', 'YYYY-MM-DD'));

INSERT INTO PRODUCT1 (PID, P_SIZE, SOFTWARE) VALUES ('948975', 'Large', 'Subin');

INSERT INTO CUSTOMER (C_NAME, ADDRESS) VALUES ('SAIED HO', '343 NORMAN');

SELECT C_NAME FROM CUSTOMER WHERE C_NAME = 'SAIED HO';

INSERT INTO PURCHASE (C_NAME, PID) VALUES ('SAIED HO', '948975');

SELECT MAX(ACNT_NO) FROM ACCOUNTS;

SELECT ACNT_NO FROM P1_ACCOUNT WHERE PID = 948975;

SELECT ACNT_NO FROM  PRODUCT1 NATURAL JOIN P1_ACCOUNT WHERE PID = 948975;

SELECT * FROM  PRODUCT WHERE PID = 9489975;


select * from product where production_date = sysdate;

INSERT INTO PRODUCT (PID, PRODUCTION_DATE, SPENT_TIME) VALUES ('23242', SYSDATE-1, '3');

INSERT INTO ACCOUNTS (ACNT_NO, ACNT_DATE, COST) VALUES ('23242', SYSDATE-1, '3.2');

INSERT INTO P1_ACCOUNT (ACNT_NO, PID) VALUES ('23242', '948975');


SELECT * FROM CUSTOMER WHERE C_NAME = 'SAEID HO';


SELECT PID FROM PURCHASE WHERE C_NAME = 'SAEID HO';

SELECT MAX(COMP_ID) FROM COMPLAINT_LIST;

INSERT INTO COMPLAINT_LIST (COMP_ID, COMP_DATE, DESCRIPTION, TREATMENT) VALUES ('1111', SYSDATE-1, 'KSDHFKJAHS', 'Exchange');

INSERT INTO COMPLAINT (COMP_ID, PID) VALUES ('1111', '948975');

SELECT * FROM PURCHASE WHERE PID = '948975' AND C_NAME = 'SAIED HO';

SELECT MAX(ACCIDENT_ID) FROM ACCIDENT_RECORD;

select * from (select PID From Produce where E_NAME = 'Eric Kennedy') where pid = 948975;

INSERT INTO ACCIDENT_RECORD (ACCIDENT_ID, ACCIDENT_DATE, WORK_DAYS) VALUES (11111, SYSDATE-1, 2); 

INSERT INTO ACCIDENT_REPAIR (ACCIDENT_ID, PID, T_NAME) VALUES (11111, 948975, 'Bonnie Porter');

SELECT E_NAME FROM PRODUCE WHERE PID = 948975;
SELECT E_NAME FROM repair WHERE PID = 948975;

SELECT PRODUCTION_DATE, SPENT_TIME FROM PRODUCT WHERE PID = 948975;

SELECT * FROM PRODUCT NATURAL JOIN PRODUCE WHERE E_NAME = 'Eric Kennedy';

SELECT COUNT(PID) FROM (SELECT * FROM PRODUCT NATURAL JOIN QC_CHECK WHERE E_NAME = 'Sara Burns') WHERE PID IN (SELECT PID FROM COMPLAINT);

SELECT SUM(COST)
FROM ACCOUNTS NATURAL JOIN P3_ACCOUNT
WHERE PID IN 
      (SELECT PID
      FROM QC_REP_REQ 
      WHERE QC_NAME = 'Stephanie Garrett');
      
      
select * 
from purchase 
where c_name = 'lori torres';

ALTER SESSION SET NLS_COMP=LINGUISTIC;
ALTER SESSION SET NLS_SORT=BINARY_CI;


SELECT C_NAME FROM PURCHASE NATURAL JOIN PRODUCT2 WHERE COLOR = 'BLUE';

SELECT * FROM COMP_REP_REQ;

SELECT * FROM ACCIDENT_REPAIR;

SELECT * FROM ACCIDENT_REPAIR NATURAL JOIN COMP_REP_REQ;

SELECT * FROM COMPLAINT NATURAL JOIN REPAIR;

SELECT * FROM REPAIR WHERE PID = 654760;

SELECT SUM(WORK_DAYS) FROM (ACCIDENT_REPAIR NATURAL JOIN COMP_REP_REQ) NATURAL JOIN ACCIDENT_RECORD;

SELECT * FROM WORKER;
SELECT C_NAME FROM CUSTOMER WHERE C_NAME IN (SELECT E_NAME FROM WORKER);

SELECT C_NAME FROM PURCHASE NATURAL JOIN PRODUCE WHERE C_NAME = E_NAME;
SELECT C_NAME FROM PURCHASE NATURAL JOIN QC_CHECK WHERE C_NAME = E_NAME;
SELECT C_NAME FROM PURCHASE NATURAL JOIN REPAIR WHERE C_NAME = E_NAME;

SELECT * FROM PURCHASE WHERE C_NAME IN (SELECT E_NAME FROM WORKER);

SELECT * FROM ACCOUNTS;

SELECT AVG(COST) FROM (SELECT * FROM ACCOUNTS WHERE ACCOUNTS.ACNT_NO IN (SELECT ACNT_NO FROM P1_ACCOUNT UNION (SELECT ACNT_NO FROM P2_ACCOUNT UNION (SELECT ACNT_NO FROM P3_ACCOUNT)))) WHERE ACNT_DATE BETWEEN '01-JAN-2014' AND '31-DEC-2014';

SELECT AVG(COST) FROM (SELECT * FROM ACCOUNTS WHERE ACCOUNTS.ACNT_NO IN (SELECT ACNT_NO FROM P1_ACCOUNT UNION (SELECT ACNT_NO FROM P2_ACCOUNT UNION (SELECT ACNT_NO FROM P3_ACCOUNT)))) WHERE ACNT_DATE BETWEEN '01-JAN-2014' AND '31-DEC-2014';

SELECT AVG(COST) FROM 
(SELECT * FROM PRODUCT WHERE PRODUCTION_DATE BETWEEN '01-JAN-2014' AND '31-DEC-2014')
NATURAL JOIN 
(SELECT * FROM P1_ACCOUNT UNION (SELECT * FROM P2_ACCOUNT UNION (SELECT * FROM P3_ACCOUNT)))
NATURAL JOIN ACCOUNTS;

SELECT * FROM QC_STAFF WHERE E_NAME = 'RAYMOND COX';
SELECT * FROM TECH_STAFF WHERE E_NAME = 'TODD SHAW';
SELECT * FROM EMPLOYEE WHERE E_NAME = 'RAYMOND COX';


INSERT INTO TECH_STAFF (E_NAME, EDUCATION, POSITION) 
VALUES((SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'RAYMOND COX'), 
      (SELECT EDUCATION FROM TECH_STAFF WHERE E_NAME = 'TODD SHAW'), 
      (SELECT POSITION FROM TECH_STAFF WHERE E_NAME = 'TODD SHAW'));
      
INSERT INTO QC_STAFF (E_NAME, TYPE_CHECK) 
VALUES((SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'TODD SHAW'), 
      (SELECT TYPE_CHECK FROM QC_STAFF WHERE E_NAME = 'RAYMOND COX'));
      
UPDATE REPAIR 
SET E_NAME = (SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'RAYMOND COX')
WHERE E_NAME = 'TODD SHAW';

UPDATE ACCIDENT_REPAIR 
SET T_NAME = (SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'RAYMOND COX')
WHERE T_NAME = 'TODD SHAW';

DELETE FROM TECH_STAFF 
WHERE E_NAME = (SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'TODD SHAW');

UPDATE QC_CHECK 
SET E_NAME = (SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'TODD SHAW')
WHERE E_NAME = 'RAYMOND COX';

UPDATE QC_REP_REQ 
SET QC_NAME = (SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'TODD SHAW')
WHERE QC_NAME = 'RAYMOND COX';

DELETE FROM QC_STAFF 
WHERE E_NAME = (SELECT E_NAME FROM EMPLOYEE WHERE E_NAME = 'RAYMOND COX');


DELETE FROM ACCIDENT_PRODUCTION WHERE ACCIDENT_ID IN (SELECT ACCIDENT_ID FROM ACCIDENT_RECORD WHERE ACCIDENT_DATE BETWEEN TO_DATE('2015-09-08', 'YYYY-MM-DD') AND TO_DATE('2016-01-08', 'YYYY-MM-DD'));

DELETE FROM ACCIDENT_REPAIR WHERE ACCIDENT_ID IN (SELECT ACCIDENT_ID FROM ACCIDENT_RECORD WHERE ACCIDENT_DATE BETWEEN TO_DATE('2015-09-08', 'YYYY-MM-DD') AND TO_DATE('2016-01-08', 'YYYY-MM-DD'));

DELETE FROM ACCIDENT_RECORD WHERE ACCIDENT_ID IN (SELECT ACCIDENT_ID FROM ACCIDENT_RECORD WHERE ACCIDENT_DATE BETWEEN TO_DATE('2015-09-08', 'YYYY-MM-DD') AND TO_DATE('2016-01-08', 'YYYY-MM-DD'));

DELETE FROM ACCIDENT_RECORD WHERE ACCIDENT_DATE BETWEEN TO_DATE('2015-09-08', 'YYYY-MM-DD') AND TO_DATE('2016-01-08', 'YYYY-MM-DD');



SELECT * FROM CUSTOMER ORDER BY C_NAME;

INSERT INTO CUSTOMER (C_NAME, ADDRESS) VALUES ('SAIED HO', '983 Astaneh');

SELECT * FROM  PRODUCT NATURAL JOIN PRODUCT3 WHERE PID = 1236;

SELECT * FROM QC_REP_REQ NATURAL JOIN P1_ACCOUNT;

SELECT DISTINCT C_NAME FROM PURCHASE NATURAL JOIN PRODUCT2 WHERE COLOR = 'Blue';

CREATE INDEX ACC_DATE ON ACCIDENT_RECORD (ACCIDENT_DATE);
CREATE INDEX ACC_REP_NAME ON ACCIDENT_REPAIR (T_NAME);
CREATE INDEX ACC_REP_PID ON ACCIDENT_REPAIR (PID);
CREATE INDEX PRODUCT_DATE ON PRODUCT (PRODUCTION_DATE);
CREATE INDEX PRODUCT_TIME ON PRODUCT (SPENT_TIME);
CREATE INDEX PRODUCE__NAME ON PRODUCE (E_NAME);
CREATE INDEX QC_CHECK__NAME ON QC_CHECK (E_NAME);
CREATE INDEX REPAIR__NAME ON REPAIR (E_NAME);
CREATE INDEX PRODUCT2_COLOR ON PRODUCT2 (COLOR);
CREATE INDEX PURCHASE_NAME ON PURCHASE (C_NAME);
CREATE INDEX P3_ACCOUNT_PID ON P3_ACCOUNT(PID);
